version: "3.4"

services:
  sio.redis:
    image: "redis:alpine"
    container_name: sio.redis
  sio.sql.store:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: sio.sql.store
  sio.storage:
    image: "mcr.microsoft.com/azure-storage/azurite"
    container_name: sio.storage
  sio.rabbitmq:
    image: "rabbitmq:3-management-alpine"
    container_name: sio.rabbitmq
networks:
  default:
    external:
      name: sio.network
