version: "3.4"

services:
  sio.sql.store:
    user: 'root'
    environment:
      SA_PASSWORD: "1qaz-pl,"
      ACCEPT_EULA: "Y"
    ports:
      - "1445:1433"
    volumes:
      - /var/opt/mssql
  sio.storage:
    ports:
      - "10000:10000"
      - "10001:10001"
    volumes:
      - /var/opt/azurite/data
  sio.rabbitmq:
    ports:
      - 15672:15672